import type { Metadata } from "next";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import { cn } from "@/lib/utils";
import { Footer, Navbar } from "@/components/index"

const inter = Inter({ subsets: ["latin"], display: "swap" });
const poppins = Poppins({ subsets: ["latin"], weight: ["600", "700"], display: "swap" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased")}
    >
      <body className={`${poppins.className} min-h-full flex flex-col`}>
        <Navbar />
        <main className="flex-1 pt-20">
        {children}
        </main>
        <Footer/>
        </body>
        
    </html>
  );
}
